/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_t2embed(void);

const struct test winetest_testlist[] =
{
    { "t2embed", func_t2embed },
    { 0, 0 }
};
