/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_atsvcapi(void);
extern void func_rpcapi(void);

const struct test winetest_testlist[] =
{
    { "atsvcapi", func_atsvcapi },
    { "rpcapi", func_rpcapi },
    { 0, 0 }
};
