/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_mediadet(void);
extern void func_nullrenderer(void);
extern void func_samplegrabber(void);
extern void func_timeline(void);

const struct test winetest_testlist[] =
{
    { "mediadet", func_mediadet },
    { "nullrenderer", func_nullrenderer },
    { "samplegrabber", func_samplegrabber },
    { "timeline", func_timeline },
    { 0, 0 }
};
