/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_msvcp140(void);

const struct test winetest_testlist[] =
{
    { "msvcp140", func_msvcp140 },
    { 0, 0 }
};
