/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_address(void);
extern void func_client(void);
extern void func_server(void);
extern void func_thread(void);

const struct test winetest_testlist[] =
{
    { "address", func_address },
    { "client", func_client },
    { "server", func_server },
    { "thread", func_thread },
    { 0, 0 }
};
