/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_device(void);
extern void func_stateblock(void);
extern void func_visual(void);

const struct test winetest_testlist[] =
{
    { "device", func_device },
    { "stateblock", func_stateblock },
    { "visual", func_visual },
    { 0, 0 }
};
