/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_dbghelp(void);

const struct test winetest_testlist[] =
{
    { "dbghelp", func_dbghelp },
    { 0, 0 }
};
