/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_device(void);
extern void func_effect(void);
extern void func_reflection(void);

const struct test winetest_testlist[] =
{
    { "device", func_device },
    { "effect", func_effect },
    { "reflection", func_reflection },
    { 0, 0 }
};
