/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_convert(void);
extern void func_database(void);
extern void func_marshal(void);

const struct test winetest_testlist[] =
{
    { "convert", func_convert },
    { "database", func_database },
    { "marshal", func_marshal },
    { 0, 0 }
};
