/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_container(void);
extern void func_provider(void);

const struct test winetest_testlist[] =
{
    { "container", func_container },
    { "provider", func_provider },
    { 0, 0 }
};
