/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_shdocvw(void);
extern void func_shortcut(void);

const struct test winetest_testlist[] =
{
    { "shdocvw", func_shdocvw },
    { "shortcut", func_shortcut },
    { 0, 0 }
};
