/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_path(void);
extern void func_sync(void);

const struct test winetest_testlist[] =
{
    { "path", func_path },
    { "sync", func_sync },
    { 0, 0 }
};
