/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_msado15(void);

const struct test winetest_testlist[] =
{
    { "msado15", func_msado15 },
    { 0, 0 }
};
