/*** Autogenerated by WIDL 5.0 from ../../include/wine/fil_data.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __fil_data_h__
#define __fil_data_h__

#ifdef __i386_on_x86_64__
#pragma clang default_addr_space(push, ptr32)
#pragma clang storage_addr_space(push, ptr32)
#endif
/* Forward declarations */

#ifndef __IAMFilterData_FWD_DEFINED__
#define __IAMFilterData_FWD_DEFINED__
typedef interface IAMFilterData IAMFilterData;
#ifdef __cplusplus
interface IAMFilterData;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <unknwn.h>
#include <strmif.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * IAMFilterData interface
 */
#ifndef __IAMFilterData_INTERFACE_DEFINED__
#define __IAMFilterData_INTERFACE_DEFINED__

DEFINE_GUID(IID_IAMFilterData, 0x97f7c4d4, 0x547b, 0x4a5f, 0x83,0x32, 0x53,0x64,0x30,0xad,0x2e,0x4d);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("97f7c4d4-547b-4a5f-8332-536430ad2e4d")
IAMFilterData : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE ParseFilterData(
        BYTE *data,
        ULONG size,
        BYTE **regfilter) = 0;

    virtual HRESULT STDMETHODCALLTYPE CreateFilterData(
        REGFILTER2 *regfilter,
        BYTE **data,
        ULONG *size) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(IAMFilterData, 0x97f7c4d4, 0x547b, 0x4a5f, 0x83,0x32, 0x53,0x64,0x30,0xad,0x2e,0x4d)
#endif
#else
typedef struct IAMFilterDataVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        IAMFilterData *This,
        REFIID riid,
        void **ppvObject);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        IAMFilterData *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        IAMFilterData *This);

    /*** IAMFilterData methods ***/
    HRESULT (STDMETHODCALLTYPE *ParseFilterData)(
        IAMFilterData *This,
        BYTE *data,
        ULONG size,
        BYTE **regfilter);

    HRESULT (STDMETHODCALLTYPE *CreateFilterData)(
        IAMFilterData *This,
        REGFILTER2 *regfilter,
        BYTE **data,
        ULONG *size);

    END_INTERFACE
} IAMFilterDataVtbl;

interface IAMFilterData {
    CONST_VTBL IAMFilterDataVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define IAMFilterData_QueryInterface(This,riid,ppvObject) (This)->lpVtbl->QueryInterface(This,riid,ppvObject)
#define IAMFilterData_AddRef(This) (This)->lpVtbl->AddRef(This)
#define IAMFilterData_Release(This) (This)->lpVtbl->Release(This)
/*** IAMFilterData methods ***/
#define IAMFilterData_ParseFilterData(This,data,size,regfilter) (This)->lpVtbl->ParseFilterData(This,data,size,regfilter)
#define IAMFilterData_CreateFilterData(This,regfilter,data,size) (This)->lpVtbl->CreateFilterData(This,regfilter,data,size)
#else
/*** IUnknown methods ***/
static FORCEINLINE HRESULT IAMFilterData_QueryInterface(IAMFilterData* This,REFIID riid,void **ppvObject) {
    return This->lpVtbl->QueryInterface(This,riid,ppvObject);
}
static FORCEINLINE ULONG IAMFilterData_AddRef(IAMFilterData* This) {
    return This->lpVtbl->AddRef(This);
}
static FORCEINLINE ULONG IAMFilterData_Release(IAMFilterData* This) {
    return This->lpVtbl->Release(This);
}
/*** IAMFilterData methods ***/
static FORCEINLINE HRESULT IAMFilterData_ParseFilterData(IAMFilterData* This,BYTE *data,ULONG size,BYTE **regfilter) {
    return This->lpVtbl->ParseFilterData(This,data,size,regfilter);
}
static FORCEINLINE HRESULT IAMFilterData_CreateFilterData(IAMFilterData* This,REGFILTER2 *regfilter,BYTE **data,ULONG *size) {
    return This->lpVtbl->CreateFilterData(This,regfilter,data,size);
}
#endif
#endif

#endif


#endif  /* __IAMFilterData_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#ifdef __i386_on_x86_64__
#pragma clang default_addr_space(pop)
#pragma clang storage_addr_space(pop)
#endif
#endif /* __fil_data_h__ */
