/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_acmwrapper(void);
extern void func_avidec(void);
extern void func_avisplit(void);
extern void func_dsoundrender(void);
extern void func_filesource(void);
extern void func_filtergraph(void);
extern void func_filtermapper(void);
extern void func_memallocator(void);
extern void func_mpegsplit(void);
extern void func_systemclock(void);
extern void func_videorenderer(void);
extern void func_vmr7(void);
extern void func_vmr9(void);
extern void func_waveparser(void);

const struct test winetest_testlist[] =
{
    { "acmwrapper", func_acmwrapper },
    { "avidec", func_avidec },
    { "avisplit", func_avisplit },
    { "dsoundrender", func_dsoundrender },
    { "filesource", func_filesource },
    { "filtergraph", func_filtergraph },
    { "filtermapper", func_filtermapper },
    { "memallocator", func_memallocator },
    { "mpegsplit", func_mpegsplit },
    { "systemclock", func_systemclock },
    { "videorenderer", func_videorenderer },
    { "vmr7", func_vmr7 },
    { "vmr9", func_vmr9 },
    { "waveparser", func_waveparser },
    { 0, 0 }
};
