/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_apply_patch(void);

const struct test winetest_testlist[] =
{
    { "apply_patch", func_apply_patch },
    { 0, 0 }
};
