/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_drawdib(void);
extern void func_mciwnd(void);
extern void func_msvfw(void);

const struct test winetest_testlist[] =
{
    { "drawdib", func_drawdib },
    { "mciwnd", func_mciwnd },
    { "msvfw", func_msvfw },
    { 0, 0 }
};
