/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_roapi(void);
extern void func_string(void);

const struct test winetest_testlist[] =
{
    { "roapi", func_roapi },
    { "string", func_string },
    { 0, 0 }
};
