/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_automation(void);
extern void func_token(void);
extern void func_tts(void);

const struct test winetest_testlist[] =
{
    { "automation", func_automation },
    { "token", func_token },
    { "tts", func_tts },
    { 0, 0 }
};
