/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_gameexplorer(void);
extern void func_gamestatistics(void);

const struct test winetest_testlist[] =
{
    { "gameexplorer", func_gameexplorer },
    { "gamestatistics", func_gamestatistics },
    { 0, 0 }
};
