/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_audiorecord(void);
extern void func_avico(void);
extern void func_avimux(void);
extern void func_qcap(void);
extern void func_smartteefilter(void);
extern void func_videocapture(void);

const struct test winetest_testlist[] =
{
    { "audiorecord", func_audiorecord },
    { "avico", func_avico },
    { "avimux", func_avimux },
    { "qcap", func_qcap },
    { "smartteefilter", func_smartteefilter },
    { "videocapture", func_videocapture },
    { 0, 0 }
};
