/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_ddrawex(void);
extern void func_surface(void);

const struct test winetest_testlist[] =
{
    { "ddrawex", func_ddrawex },
    { "surface", func_surface },
    { 0, 0 }
};
