/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_netcfgx(void);

const struct test winetest_testlist[] =
{
    { "netcfgx", func_netcfgx },
    { 0, 0 }
};
