/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_msvcp120(void);

const struct test winetest_testlist[] =
{
    { "msvcp120", func_msvcp120 },
    { 0, 0 }
};
