/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_createobj(void);
extern void func_run(void);
extern void func_vbscript(void);

const struct test winetest_testlist[] =
{
    { "createobj", func_createobj },
    { "run", func_run },
    { "vbscript", func_vbscript },
    { 0, 0 }
};
