/* Automatically generated by make depend; DO NOT EDIT!! */

#define WIN32_LEAN_AND_MEAN
#include <windows.h>

#define STANDALONE
#include "wine/test.h"

extern void func_channel(void);
extern void func_msg(void);
extern void func_proxy(void);
extern void func_reader(void);
extern void func_url(void);
extern void func_writer(void);

const struct test winetest_testlist[] =
{
    { "channel", func_channel },
    { "msg", func_msg },
    { "proxy", func_proxy },
    { "reader", func_reader },
    { "url", func_url },
    { "writer", func_writer },
    { 0, 0 }
};
